site_name: Uniview
site_url: https://uniview.qupa.org/
repo_name: Uniview
repo_url: https://github.com/qupa-project/uniview/
edit_uri: https://github.com/qupa-project/uniview-docs/tree/main/docs
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github-square
  features:
    - search.suggest
    - header.autohide
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - toc.integrate
  palette:
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: en
plugins:
  - search:
      prebuild_index: true
  # - offline
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dqcenR2n6m
    - icon: fontawesome/brands/github
      link: https://github.com/qupa-lang/uniview
copyright: Copyright &copy; 2021 Ajani James Bilby


nav:
  - Home: index.md
  - Docs:
    - Installation:
      - setup/index.md
    - Variables and Values:
      - variables/index.md
      - variables/declaration.md
      - variables/type-systems.md
    - First Execution:
      - first-execution/index.md
      - first-execution/hello-world.md
      - first-execution/arguments.md
    - Functions: functions.md
    - Expressions: expressions.md
    - Flow Control:
      - flow-control/index.md
      - flow-control/if-statements.md
    - Structures: structures/index.md
    - Classes: classes/index.md
    - Interfacing with Foreign Functions:
      - ffi/index.md
      - ffi/include.md
      - ffi/lending.md
      - ffi/structures.md
      - ffi/primitives.md
  - API:
    - Builtins:
      - builtins/index.md
      - builtins/typecast.md
      - builtins/sizeof.md
      - builtins/bitcast.md
    - Standard Library: std/index.md
  - Qupa: https://www.qupa.org/