site_name: Uniview
site_url: https://uniview.qupa.org/
site_description: View once immutability enabling the safeties of immutable code, while enjoying near procedural performance
repo_name: Uniview Language
repo_url: https://github.com/qupa-project/uniview-lang
edit_uri: https://github.com/qupa-project/uniview-docs/tree/main/docs
theme:
  name: material
  favicon: /icon/unicycle.png
  custom_dir: overrides
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
    logo: material/unicycle
  features:
    - search.suggest
    - header.autohide
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: pink
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: pink
      accent: purple
  language: en
plugins:
  - search:
      prebuild_index: true
  # - offline
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - styles/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dqcenR2n6m
    - icon: fontawesome/brands/github
      link: https://github.com/qupa-project/uniview-lang
copyright: Copyright &copy; 2021 Ajani James Bilby


nav:
  - Home: index.md

  - Guide: guide/index.md

  - Installation:
      - installation/index.md

  - Tutorial:
    - Foundations:
      - guide/tutorial/index.md
      - Variables: guide/tutorial/foundation/variable.md
      - Functions: guide/tutorial/foundation/function.md
      - Lending: guide/tutorial/foundation/lend.md
      - Branches: guide/tutorial/foundation/branch.md
      - Structures: guide/tutorial/foundation/structure.md
      - Traits: guide/tutorial/foundation/trait.md
    - Iteration:
      - guide/tutorial/iteration/index.md
      - Generators: guide/tutorial/iteration/generator.md

  - API:
    - api/index.md
    - Built-ins:
      - api/built-ins/index.md
      - api/built-ins/typecast.md
      - api/built-ins/sizeof.md
      - api/built-ins/bit-cast.md
    - Standard Library:
      - api/std/index.md
      - String: api/std/string.md
      - Memory: api/std/memory.md

  - Manual:
    - guide/manual/index.md
    - Variables: guide/manual/variables.md
    - Lending: guide/manual/lending.md
    - Functions: guide/manual/functions.md
    - Structures: guide/manual/structures.md
    - Traits: guide/manual/traits.md
    - Types: guide/manual/types.md
    - Return: guide/manual/return.md

  # Deprecated
  - Novice:
    - Variables and Values:
      - guide/variables/index.md
      - guide/variables/declaration.md
      - guide/variables/type-systems.md
    - First Execution:
      - guide/first-execution/index.md
      - guide/first-execution/hello-world.md
      - guide/first-execution/arguments.md
    - Functions: guide/functions.md
    - Expressions: guide/expressions.md
    - Flow Control:
      - guide/flow-control/index.md
      - guide/flow-control/if-statements.md
    - Structures: guide/structures/index.md
    - Classes: guide/classes/index.md
    - Interfacing with Foreign Functions:
      - guide/ffi/index.md
      - guide/ffi/include.md
      - guide/ffi/lending.md
      - guide/ffi/structures.md
      - guide/ffi/primitives.md